### ISSUE TITLE
设备都已经连接，订阅也已成功，就是writeBLECharacteristicValue，api，毫无反应。没有任何失败或者成功之类的任何回调。？？？

### ISSUE THREAD

**Issue by virgouss** [pkkhandsome/uniapp-sand-plugin-bluetooth#1]

**Comment by pkkhandsome** [comment]
// 监听特征值变化
BLE.onBLECharacteristicValueChange(function(res){

});

//写特征值
BLE.writeBLECharacteristicValue({
            deviceId,
            serviceId,
            characteristicId,
            value,
            success(res) {},
            fail(res) {}
});

没反应需先确认deviceId,serviceId,characteristicId,value 的正确性  设备端抓包看是否有接收和回复
